// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCare.API.Data;

#nullable disable

namespace PetCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930124156_FixEncodingIssues")]
    partial class FixEncodingIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetCare.API.Models.EventTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("EventTypeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Color = "blue",
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "local_hospital",
                            Name = "Visita Veterinaria"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Color = "orange",
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "medication",
                            Name = "Medicación"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Color = "red",
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "vaccines",
                            Name = "Vacunación"
                        });
                });

            modelBuilder.Entity("PetCare.API.Models.HealthEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("HealthEventType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentVisitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("ParentVisitId");

                    b.HasIndex("PetId");

                    b.ToTable("HealthEvents");

                    b.HasDiscriminator<string>("HealthEventType").HasValue("HealthEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetCare.API.Models.HealthEventOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HealthEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HealthEventId");

                    b.ToTable("HealthEventOccurrences");
                });

            modelBuilder.Entity("PetCare.API.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetCare.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetCare.API.Models.CustomHealthEvent", b =>
                {
                    b.HasBaseType("PetCare.API.Models.HealthEvent");

                    b.Property<int>("FrequencyUnit")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Custom");
                });

            modelBuilder.Entity("PetCare.API.Models.MedicationEvent", b =>
                {
                    b.HasBaseType("PetCare.API.Models.HealthEvent");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FrequencyUnit")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("HealthEvents", t =>
                        {
                            t.Property("FrequencyUnit")
                                .HasColumnName("MedicationEvent_FrequencyUnit");

                            t.Property("FrequencyValue")
                                .HasColumnName("MedicationEvent_FrequencyValue");
                        });

                    b.HasDiscriminator().HasValue("Medication");
                });

            modelBuilder.Entity("PetCare.API.Models.VaccineEvent", b =>
                {
                    b.HasBaseType("PetCare.API.Models.HealthEvent");

                    b.Property<int>("FrequencyUnit")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("HealthEvents", t =>
                        {
                            t.Property("FrequencyUnit")
                                .HasColumnName("VaccineEvent_FrequencyUnit");

                            t.Property("FrequencyValue")
                                .HasColumnName("VaccineEvent_FrequencyValue");
                        });

                    b.HasDiscriminator().HasValue("Vaccine");
                });

            modelBuilder.Entity("PetCare.API.Models.VetVisitEvent", b =>
                {
                    b.HasBaseType("PetCare.API.Models.HealthEvent");

                    b.Property<string>("ClinicName")
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHospitalization")
                        .HasColumnType("boolean");

                    b.Property<string>("VeterinarianName")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("VetVisit");
                });

            modelBuilder.Entity("PetCare.API.Models.EventTypeDefinition", b =>
                {
                    b.HasOne("PetCare.API.Models.User", null)
                        .WithMany("EventTypeDefinitions")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("PetCare.API.Models.HealthEvent", b =>
                {
                    b.HasOne("PetCare.API.Models.EventTypeDefinition", "EventType")
                        .WithMany("HealthEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.VetVisitEvent", "ParentVisit")
                        .WithMany()
                        .HasForeignKey("ParentVisitId");

                    b.HasOne("PetCare.API.Models.Pet", "Pet")
                        .WithMany("HealthEvents")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("ParentVisit");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.API.Models.HealthEventOccurrence", b =>
                {
                    b.HasOne("PetCare.API.Models.HealthEvent", "HealthEvent")
                        .WithMany()
                        .HasForeignKey("HealthEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthEvent");
                });

            modelBuilder.Entity("PetCare.API.Models.Pet", b =>
                {
                    b.HasOne("PetCare.API.Models.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetCare.API.Models.EventTypeDefinition", b =>
                {
                    b.Navigation("HealthEvents");
                });

            modelBuilder.Entity("PetCare.API.Models.Pet", b =>
                {
                    b.Navigation("HealthEvents");
                });

            modelBuilder.Entity("PetCare.API.Models.User", b =>
                {
                    b.Navigation("EventTypeDefinitions");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
